/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#294e3f",
        "surface-container": "#edeeef",
        "inverse-primary": "#c3c0ff",
        "surface-container-high": "#e7e8e9",
        "on-surface-variant": "#464553",
        "surface-container-low": "#f3f4f5",
        "on-primary-fixed-variant": "#3b35a7",
        "outline-variant": "#c8c4d5",
        "on-primary-container": "#a9a7ff",
        "background": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "tertiary": "#003421",
        "primary-fixed": "#e2dfff",
        "error-container": "#ffdad6",
        "surface-tint": "#544fc0",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#6ffbbe",
        "on-surface": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#c3ecd7",
        "on-primary-fixed": "#0f0069",
        "on-secondary-container": "#476c5b",
        "surface-variant": "#e1e3e4",
        "secondary": "#416656",
        "on-secondary": "#ffffff",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed": "#002113",
        "tertiary-container": "#004d33",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#2dc68d",
        "secondary-fixed-dim": "#a8cfbc",
        "on-secondary-fixed": "#002115",
        "on-primary": "#ffffff",
        "secondary-container": "#c3ecd7",
        "primary-container": "#3730a3",
        "surface": "#f8f9fa",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "outline": "#777584",
        "error": "#ba1a1a",
        "on-background": "#191c1d",
        "primary": "#1f108e",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
      },
    },
  },
  plugins: [],
}
